name: Deploy Image

on:
  workflow_dispatch:
    inputs:
        instance-id:
          description: 'The ID of the instance to deploy to'
          required: true
          type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # AWS OIDC
  contents: read # Checkout

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/github-oidc-role
          aws-region: us-east-1
      - name: Check out repository code
        uses: actions/checkout@v3